-- Seed sample properties for Roommates platform
-- Only uses columns that exist in the actual schema

INSERT INTO public.properties (
  landlord_id,
  public_code,
  title,
  street_address,
  address,
  city,
  state,
  postal_code,
  rent_total,
  rent_amount,
  total_bedrooms,
  bedrooms,
  total_bathrooms,
  square_feet,
  description,
  min_household_income,
  min_household_income_monthly,
  max_occupants,
  available_from,
  available_rooms,
  is_active,
  status
)
VALUES
(
  (SELECT id FROM auth.users ORDER BY created_at LIMIT 1),
  'RM-NY-000001',
  'View 34 – Studio / 1BR in Manhattan',
  '401 W 34th St',
  '401 W 34th St, New York, NY 10001',
  'New York',
  'NY',
  '10001',
  3300,
  3300,
  1,
  1,
  1,
  550,
  'Modern high-rise in Manhattan with amenities and fitness center. Perfect for young professionals.',
  9900,
  9900,
  2,
  CURRENT_DATE + INTERVAL '15 days',
  1,
  TRUE,
  'active'
),
(
  (SELECT id FROM auth.users ORDER BY created_at LIMIT 1),
  'RM-CT-000001',
  '34 Woodland St – 3BR House in New Haven',
  '34 Woodland St',
  '34 Woodland St, New Haven, CT 06511',
  'New Haven',
  'CT',
  '06511',
  3100,
  3100,
  3,
  3,
  1.5,
  1400,
  'Three-bedroom New Haven rental near universities. Great for students or young professionals.',
  9300,
  9300,
  4,
  CURRENT_DATE + INTERVAL '30 days',
  3,
  TRUE,
  'active'
),
(
  (SELECT id FROM auth.users ORDER BY created_at LIMIT 1),
  'RM-CT-000002',
  'Farmington 4BR House with Garage',
  '123 Farmington Ave',
  '123 Farmington Ave, Farmington, CT 06032',
  'Farmington',
  'CT',
  '06032',
  5500,
  5500,
  4,
  4,
  2.5,
  2200,
  'Large single-family Farmington home with driveway and yard. Perfect for families or groups.',
  16500,
  16500,
  5,
  CURRENT_DATE + INTERVAL '45 days',
  4,
  TRUE,
  'active'
)
ON CONFLICT (public_code) DO UPDATE
SET
  rent_total = EXCLUDED.rent_total,
  rent_amount = EXCLUDED.rent_amount,
  total_bedrooms = EXCLUDED.total_bedrooms,
  bedrooms = EXCLUDED.bedrooms,
  total_bathrooms = EXCLUDED.total_bathrooms,
  description = EXCLUDED.description,
  updated_at = NOW();